development:
  adapter: postgresql
  encoding: unicode
  database: felipe-homepage_development
  pool: 5
  username: felipems
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: felipe-homepage_test
  pool: 5
  username: felipems
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: felipe-homepage_production
  pool: 5
  username: felipems
  password:

  
